---
title: "04_Correlation_test"
author: "Erick Bolaños Duran"
date: "2023-03-23"
output:
    rmdformats::readthedown:
    code_folding: show
    highlight: kate
    toc_depth: 2
    number_sections: no
    self_contained: true
editor_options: 
  markdown: 
    wrap: 72
---

```{=html}
<style>
  #content {
    max-width: 1400px;
  }
  #sidebar h2 {
    background-color: #008B8B;
  }
  
  h1, h2 {
    color: #008B8B;
  }
</style>
```
```{r setup, include=FALSE}

#No MOVER!!!!!

knitr::opts_chunk$set(warning=FALSE, message=FALSE, #error=FALSE,
                      echo = TRUE,
                      fig.path="figures_Rtemplate/",
                      #dev='pdf', #Activar esta opción si se quiere obtener PDF
                      fig.width = 8,
                      fig.height = 4,
                      fig.align="center")
```

```{r, warning=FALSE, message=FALSE, fig.align="center", fig.width=4, fig.height=2, fig.cap="Fig.1 Correlation among environmental variables"}
## ==============================================================
  
  # Title:04_Correlation test
  # Author details: Erick Bolaños Duran
  # Contact details: ebduran@pg.cibnor.mx
  # Script and data info: This script help to perform a correlation test to avoid collinearity
  # Copyright (c): 2023 Erick Bolaños Duran

## ==============================================================

  
## Dependencies ==============================================================
library(rerddapXtracto)
library(lubridate)
library(ncdf4)
library(httr)
library(rgdal)
library(spatialEco)
library(raster)
library(dplyr)
library(tidyr)
library(lubridate)
library(data.table)
library(rgeos)
library(sp)
library(usdm)
library(raster)
library(sf)
library(udunits2)
library(rnaturalearth) 
library(rnaturalearthdata)
library(corrplot)
###Open environmental data
varPOT=list.files(path="~/Doctorado/CIBNOR/fourth semester/01_Paper_submition/02_Data/04_Data_masked/",full.names = T,pattern = ".tif$",all.files=TRUE)
rast_POT <- stack(varPOT)
layer_names <- c("OM_SST","OSD_SST","MaxMM_SST","MinMM_SST","OM_SSS", "OSD_SSS", "OM_Kd490", "OSD_Kd490",
              "OM_Cha", "OSD_cha","OM_pH","OSD_pH","OM_SCV","OSD_SCV")
names(rast_POT)
names(rast_POT) <- layer_names
names(rast_POT)
####convert data into a data frame
env_df <- rasterToPoints(rast_POT)
head(env_df)
# If a row contains NAs remove it
# Through layers because they have different land masks
env_df <- na.omit(env_df)
env_df <- env_df[,c(3:16)]#to cut the two first columns that have coordinates data
head(env_df)#To see the first lines of each column
correl <- cor(env_df, method='pearson')
corrplot(correl, type="upper", order="hclust")
corrplot(round(correl,1), type="upper", order="hclust", method="number", tl.cex=0.6)
#A of pearson correlation will be used acording to 
#OSD_SST and MMmin_SST 0.90
#OM_SST and MMmin SST 1.00
#OSD_SSS and OM_SSS -0.80
#OM_SST and  MaxMM  0.80
#OSD_SCV and OM_SCV 0.90
#OM_KD and OM_cha 1.00
#OSD_KD and OM_cha 0.80
####After evaluation of  correlation test, we keep MaxMM_SST,Min_SST, OM_SSS, OM_KD, OM_pH, OSD_pH, OM_SCV
# We create a new corplot without the corralated data
env_df_clean <- env_df[,-c(1,2,6,8,9,10,14)]
head(env_df_clean)
correl_clean <- cor(env_df_clean, method='pearson')
corrplot(correl_clean, type="upper", order="hclust")
corrplot(round(correl_clean,1), type="upper", order="hclust", method="number", tl.cex=0.6)
###Save non correlated data into a new folder 
nocorenv <- rast_POT[[-c(1,2,6,8,9,10,14)]]
plot(nocorenv)
setwd("C:/Users/Erick Bolaños Durán/Documents/Doctorado/CIBNOR/fourth semester/01_Paper_submition/02_Data/05_Non_correlated_data/")
lapply(names(nocorenv), function(x){
  writeRaster(nocorenv[[x]], paste0(x,".tif"),overwrite=TRUE)})
```
